Cywriter/step/models.py
from .. import db

class Step(db.Model):
    __tablename__ = 'step'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Step {}>'.format(self.name)

Cywriter/step/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TimeField, DateField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo
from .models import Step

class StepForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Add Step')

Cywriter/step/__init__.py
from flask import Blueprint

step_bp  = Blueprint('step_bp', __name__, template_folder='templates')

from . import views

Cywriter/step/views.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from .models import Step
from ..spec.models import Spec
from .forms import StepForm
from . import step_bp
from .. import db
from datetime import datetime

@step_bp.route('/steps/<int:spid>')
@login_required
def steps(spid):
    user = current_user
    spec = Spec.query.get(spid)

    steps = Step.query.all() # filter by spec_id, no mater who created

    return render_template('step/steps.html', spec_id=spid, title='Spec steps', spec=spec, steps=steps, user=user)


@step_bp.route('/delete-step/<int:stid>', methods=['GET', 'POST'])
@login_required
def delete_step(stid):
    check= None
    user = current_user
    # spec = Spec.query.filter_by(id=int(id), author=user).one()
    step = Spec.query.get(id=int(stid))
    spec_id = step.spec_id

    if not spec:
        check = 'Delete error, please let administrator know.'
        return redirect(url_for('step_bp.steps', check=check))

    db.session.delete(spec)
    db.session.commit()
    flash("Spec id={} has been deleted".format(stid))

    return redirect(url_for('home_bp.homepage'))


@step_bp.route('/edit-step/<int:stid>', methods=['GET', 'POST'])
@login_required
def edit_step(stid):
    check = None
    user = current_user
    # find spec id by step id
    step = Step.query.filter_by(id=stid)
    spec_id = step.spec_id 
    spec = Spec.query.get(spec_id)


    form = StepForm()

    if request.method == "POST":
        if form.validate_on_submit():
            step= Step(name=form.name.data)
            db.session.add(step)
            db.session.commit()
            flash('New is added in')

            return redirect(url_for('step_bp.steps', spec_id=spec_id))

    return render_template('step/steps.html', title='Create step', form=form, spec=spec, step=step, check=check)


@step_bp.route('/add-step/<int:spid>', methods=['GET', 'POST'])
@login_required
def add_step(spid):
    check = None
    user = current_user
    spec = Spec.query.get(spid)
    print(spec)

    steps = Step.query.all() # filter by spec_id but now with user_id

    print('hello {}'.format(user))
    print(steps)

    form = StepForm()

    if request.method == "POST":
        if form.validate_on_submit():
            step= Step(name=form.name.data)
            db.session.add(step)
            db.session.commit()
            flash('New is added in')

            return redirect(url_for('step_bp.steps'))

    return render_template('step/steps.html', title='Create step', form=form, spec=spec, steps=steps, check=check)



@step_bp.route('/create-step/<int:spid>', methods=['GET', 'POST'])
@login_required
def steps2(spid):
    check = None
    user = current_user
    spec = Spec.query.get(spid)

    steps = Step.query.all()

    print('hello {}'.format(user))
    print(step)

    form = StepForm()

    if request.method == "POST":
        if request.form.get('stepDelete') is not None:
            deleteStep = request.form.get('checkedbox')
            if deleteStep is not None:
                step = Step.query.filter_by(id=int(deleteStep)).one()
                db.session.delete(step)
                db.session.commit()
                return redirect(url_for('step_bp.steps'))
            else:
                check = 'Please check-box of step to be deleted'

        elif form.validate_on_submit():
            step= Step(name=form.name.data)
            db.session.add(step)
            db.session.commit()
            flash('Congratulations, you just added a new step')
            return redirect(url_for('step_bp.steps'))

    return render_template('step/steps.html', title='Create step', form=form, spec=spec, steps=steps, check=check)



@step_bp.route('/add-step2/<int:spid>', methods=['GET', 'POST'])
@login_required
def add_step2(spid):
    check = None
    user = current_user
    spec = Spec.query.get(spid)

    steps = Step.query.all()

    print('hello {}'.format(user))
    print(step)

    form = StepForm()

    if request.method == "POST":
        if request.form.get('stepDelete') is not None:
            deleteStep = request.form.get('checkedbox')
            if deleteStep is not None:
                step = Step.query.filter_by(id=int(deleteStep)).one()
                db.session.delete(step)
                db.session.commit()
                return redirect(url_for('step_bp.steps'))
            else:
                check = 'Please check-box of step to be deleted'

        elif form.validate_on_submit():
            step= Step(name=form.name.data)
            db.session.add(step)
            db.session.commit()
            flash('Congratulations, you just added a new step')
            return redirect(url_for('step_bp.steps'))

    return render_template('step/steps.html', title='Create step', form=form, spec=spec, steps=steps, check=check)

Cywriter/step/templates/step/add_step.html
{% extends "base.html" %}

{% block content %}

<div django-app="TaskManager" class="task_content categories">
  <div class="">
    <div class="content">
      <div class="welcome">
        <button id="openbutton" class="openbtn" >&#9776;</button>
        <span class="welcome-text">Manage Steps</span> 
      </div>

      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="inputContainer Task">
          {{ form.name.label }}<br>
          {{ form.name(size=20) }}
          {% for error in form.name.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="buttons">   
          {{ form.submit(class="taskAdd btn") }}
        </div> 
      </form>

      <!-- Task Delete Error alert -->
      {% if check %}
      <div class="alert alert-warning" role="alert">
        <span class="closebtns" onclick="this.parentElement.style.display='none';">&times;</span>
        {{check}}
      </div>
      {% endif %}
      <!-- End Task Delete error alert -->

      <form action="" method="post">
        {{ form.hidden_tag() }} <!-- csrf token for security -->
        <div>
          <!-- tab-content -->
          <div>
            <section>
              <ul class="taskList">        
                {% for step in steps %} 
                <li class="currentTaskItem">
                  <input type="checkbox" class="taskCheckbox" name="checkedbox" id="{{ step.id }}" value="{{ step.id }}" >
                  <label for="{{ step.id }}"><span class="complete-">{{ step.name }}</span></label>
                  <button class="taskDelete " name="stepDelete" formnovalidate="" type="submit" ><i class="fa fa-trash-o icon"></i></button>
                </li>     
                {% endfor %}
              </ul> <!--end All-its-List -->
            </section>
          </div><!-- end tab content -->
        </div><!-- end tab effect -->
      </form>

    </div><!-- end content -->
  </div><!-- container -->
</div>
{% endblock %}

Cywriter/step/templates/step/steps.html
{% extends "base.html" %}

{% block content %}

<div django-app="TaskManager" class="task_content categories">
  <div class="">
    <div class="content">
      <div class="welcome">
        <button id="openbutton" class="openbtn" >&#9776;</button>
        <span class="welcome-text">Steps of {% if spec.id %} {{ spec.name }} {% endif %}</span> 
      </div>

      <div>
        <!-- tab-content -->
        <div>
          <section>
            <ul class="taskList">        
              {% for step in steps %} 
              <li class="currentTaskItem">
                <label for="{{ step.id }}"><span class="complete-">{{ step.name }}</span></label>
                <span class="taskDelete"><a href="{{ url_for('step_bp.edit_step', step_id=step.id) }}"><i class="fa fa-pencil icon"></i></a></span>
                <span class="taskDelete"><a href="{{ url_for('step_bp.delete_step', step_id=step.id) }}"><i class="fa fa-trash-o icon"></i></a></span>
              </li>     
              {% endfor %}
            </ul> <!--end All-its-List -->
          </section>
        </div><!-- end tab content -->
      </div><!-- end tab effect -->

    </div><!-- end content -->
  </div><!-- container -->
</div>

{% endblock %}